# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heft < Formula
  desc "Tool to view container images needed by Helm, for use in SBOM or air-gapped environments"
  homepage "https://github.com/tonur/heft"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tonur/heft/releases/download/v0.0.4/heft-0.0.4-darwin-x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d06f8fc3e409b0e7d516516c7a6ea6fed433dd8c0cc5adb5caa186eda6bb626d"

      def install
        bin.install "heft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tonur/heft/releases/download/v0.0.4/heft-0.0.4-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b82a88ff0cc2d8e26c6002985980ef281be6fafbaf30538efd45547df68a947c"

      def install
        bin.install "heft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tonur/heft/releases/download/v0.0.4/heft-0.0.4-linux-x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "71ec3fae9b5afb27b8cb11a7db7a1e165bca9be11cd16e028d77f4425bbafc93"
      def install
        bin.install "heft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tonur/heft/releases/download/v0.0.4/heft-0.0.4-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "16950ef062d8b68ed0f204ec769d1094ec07626bda4a5c85939fc4400948bcf9"
      def install
        bin.install "heft"
      end
    end
  end

  test do
    system "#{bin}/heft version"
  end
end
