# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heft < Formula
  desc "Tool to view container images needed by Helm, for use in SBOM or air-gapped environments"
  homepage "https://github.com/tonur/heft"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tonur/heft/releases/download/v0.0.3/heft-0.0.3-darwin-x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1ecc4b28b8b8c6a62249b3d2b53a33c2b49fe270277e4ff3a5cb4b1cec195f44"

      def install
        bin.install "heft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tonur/heft/releases/download/v0.0.3/heft-0.0.3-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "932c8d57b68a4e682016a3147289748fa4228cf045f3b8314fd9203f0ceb5727"

      def install
        bin.install "heft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tonur/heft/releases/download/v0.0.3/heft-0.0.3-linux-x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b52546aacc1db1d935ac20166348722983e8b497c16e045930e02f6d37745b6a"
      def install
        bin.install "heft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tonur/heft/releases/download/v0.0.3/heft-0.0.3-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b80e92bd03012347ba4cf0b01c0f7190e84372b2edbb4f7e851040c681fbec5e"
      def install
        bin.install "heft"
      end
    end
  end

  test do
    system "#{bin}/heft version"
  end
end
