# This file was generated by GoReleaser. DO NOT EDIT.
cask "wifitui" do
  name "wifitui"
  desc "Connect to known WiFi networks and store profiles, all from the terminal"
  homepage "https://github.com/tonur/wifitui"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wifitui"

  on_macos do
    on_intel do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-darwin-x86_64.tar.gz"
      sha256 "bc1be5a7d0058a0663e2c9a8909693f725beb612ce97d2cbfc06889b7c85e7d6"
    end
    on_arm do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-darwin-arm64.tar.gz"
      sha256 "4fa0b9f6d64d01f5ad855b9e753d79048880406c9f6258229e4f10df0f68c7ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-linux-x86_64.tar.gz"
      sha256 "f330416c35e8c40e28651d7a12929d51a56fd0c993652839dce0ed226762c794"
    end
    on_arm do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-linux-arm64.tar.gz"
      sha256 "2dd1eb808e8b4a18b4b9b180ef06e746a3d4ef357431364d02e0a68fdbafd46a"
    end
  end

  # No zap stanza required
end
